# Generated by Django 6.0.6 on 2026-07-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('speech', 'Speech Recognition'), ('translation', 'Translation'), ('tts', 'Text to Speech')], max_length=20)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('target_language', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='history/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Record',
                'verbose_name_plural': 'History Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
