# Generated by Django 6.0.6 on 2026-07-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('recognized_text', models.TextField()),
                ('duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speech Record',
                'verbose_name_plural': 'Speech Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
