# Generated by Django 6.0.6 on 2026-07-09 09:57

import speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechrecord',
            name='detected_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='speechrecord',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speechrecord',
            name='audio_file',
            field=models.FileField(max_length=500, upload_to=speech.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='speechrecord',
            name='recognized_text',
            field=models.TextField(blank=True),
        ),
    ]
